/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ToDoListController;
import DatabaseAccess.TaskDAO;
import Model.Task;
import java.util.List;

/**
 *
 * @author SONY
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    public void addCreateTaskListener(java.awt.event.ActionListener listener) {
        addTaskButton.addActionListener(listener); 
    }

    // Mở cổng cho nút "Thay đổi trạng thái"
    public void addUpdateStatusListener(java.awt.event.ActionListener listener) {
        updateTaskButton.addActionListener(listener);
    }
    
    public void addDeleteTaskListener(java.awt.event.ActionListener listener) {
        deleteTaskButton.addActionListener(listener);
    }
    
    // 2. CÁC HÀM HỖ TRỢ ĐỂ CONTROLLER LẤY DỮ LIỆU ĐANG CHỌN TRÊN BẢNG
    public int getSelectedTaskId() {
        int selectedRow = taskTable.getSelectedRow();
        if (selectedRow != -1) {
            return (int) taskTable.getValueAt(selectedRow, 0); // Cột 0 là ID
        }
        return -1; // Trả về -1 nếu người dùng chưa chọn dòng nào
    }

    public String getSelectedTaskStatus() {
        int selectedRow = taskTable.getSelectedRow();
        if (selectedRow != -1) {
            return (String) taskTable.getValueAt(selectedRow, 2); // Cột 2 là Status
        }
        return null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lableToDoList = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taskTable = new javax.swing.JTable();
        updateTaskButton = new javax.swing.JButton();
        addTaskButton = new javax.swing.JButton();
        deleteTaskButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lableToDoList.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lableToDoList.setText("TO DO LIST");

        taskTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Content", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(taskTable);
        if (taskTable.getColumnModel().getColumnCount() > 0) {
            taskTable.getColumnModel().getColumn(0).setPreferredWidth(50);
            taskTable.getColumnModel().getColumn(1).setPreferredWidth(200);
            taskTable.getColumnModel().getColumn(2).setPreferredWidth(200);
        }

        updateTaskButton.setText("Thay đổi trạng thái");
        updateTaskButton.addActionListener(this::updateTaskButtonActionPerformed);

        addTaskButton.setBackground(new java.awt.Color(51, 255, 51));
        addTaskButton.setText("Thêm Task");
        addTaskButton.addActionListener(this::addTaskButtonActionPerformed);

        deleteTaskButton.setBackground(new java.awt.Color(255, 51, 0));
        deleteTaskButton.setForeground(new java.awt.Color(242, 242, 242));
        deleteTaskButton.setText("Xoá Task");
        deleteTaskButton.addActionListener(this::deleteTaskButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lableToDoList)
                        .addGap(12, 12, 12)
                        .addComponent(addTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateTaskButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lableToDoList))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addTaskButton)
                            .addComponent(updateTaskButton)
                            .addComponent(deleteTaskButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTaskButtonActionPerformed

    }//GEN-LAST:event_updateTaskButtonActionPerformed

    private void addTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTaskButtonActionPerformed
               // TODO add your handling code here:
    }//GEN-LAST:event_addTaskButtonActionPerformed

    private void deleteTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTaskButtonActionPerformed
            // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_deleteTaskButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Hàm này sẽ được Controller gọi để đổ dữ liệu vào bảng
    // Bỏ từ khóa 'static' để hàm có thể truy cập vào biến 'taskTable'
    public void displayData(List<Task> danhSach) {
        // 1. Lấy model cấu trúc của bảng đã được NetBeans tạo sẵn
        javax.swing.table.DefaultTableModel tableModel = (javax.swing.table.DefaultTableModel) taskTable.getModel();
        
        // 2. Xóa toàn bộ dữ liệu cũ (nếu có) trước khi tải mới
        tableModel.setRowCount(0); 
        
        // 3. Duyệt qua danh sách và thêm từng dòng vào bảng
        // (Giả định class Task của bạn có các hàm getter tương ứng)
        for (Task task : danhSach) {
            Object[] rowData = {
                task.getId(), 
                task.getContent(), 
                task.getStatus()
            };
            tableModel.addRow(rowData);
        }
    }
    
    // Thêm một hàm tiện ích để Controller tiện gọi thông báo
    public void displayNotation(String thongBao, boolean laThanhCong) {
        if (laThanhCong) {
            javax.swing.JOptionPane.showMessageDialog(this, thongBao);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, thongBao, "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTaskButton;
    private javax.swing.JButton deleteTaskButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lableToDoList;
    private javax.swing.JTable taskTable;
    private javax.swing.JButton updateTaskButton;
    // End of variables declaration//GEN-END:variables
}
