/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package DatabaseAccess;

import static Database.DBConnection.getConnection;
import Model.Task;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author SONY
 */
public class TaskDAO {
    public List<Task> getAllTasks() {
        List<Task> list = new ArrayList<>();
        String sql = "SELECT * FROM TASK ORDER BY ID";
        
        try (Connection conn = getConnection();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql)) {
            
            while (rs.next()) {
                Task t = new Task(
                    rs.getInt("ID"),
                    rs.getString("CONTENT"),
                    rs.getString("STATUS")
                );
                list.add(t);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return list;
    }
    
    public boolean createTask(Task task) {
        // Câu lệnh SQL dùng các dấu chấm hỏi (?) làm tham số ẩn
        // Ta bỏ qua cột ID vì Oracle đã tự động tăng (GENERATED BY DEFAULT)
        String sql = "INSERT INTO TASK (CONTENT) VALUES (?)";
        
        // Sử dụng try-with-resources để Java tự động đóng kết nối (Connection và PreparedStatement)
        try (Connection conn = getConnection(); 
            PreparedStatement pstmt = conn.prepareStatement(sql)) {
             
            // 1. Gán giá trị thật cho các dấu ? (Vị trí đếm từ 1)
            pstmt.setString(1, task.getContent());
            
            // 2. Thực thi câu lệnh INSERT
            int rowsAffected = pstmt.executeUpdate();
            
            // 3. Nếu rowsAffected > 0 nghĩa là đã chèn thành công ít nhất 1 dòng
            return rowsAffected > 0;
            
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }
    // Hàm cập nhật trạng thái của Task dựa vào ID
    public boolean updateStatus(int id, String newStatus) {
        String sql = "UPDATE TASK SET STATUS = ? WHERE ID = ?";
        
        try (Connection conn = getConnection(); 
            PreparedStatement pstmt = conn.prepareStatement(sql)) {
             
            // Gán dữ liệu cho các dấu chấm hỏi (?)
            pstmt.setString(1, newStatus);
            pstmt.setInt(2, id);
            
            // Thực thi và kiểm tra số dòng bị ảnh hưởng
            int rowsAffected = pstmt.executeUpdate();
            return rowsAffected > 0;
            
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }
    
    // Hàm xoá Task dựa vào ID
    public boolean deleteTask (int id) {
        String sql = "DELETE FROM TASK WHERE ID = ?";
        
        try (Connection conn = getConnection(); 
            PreparedStatement pstmt = conn.prepareStatement(sql)) {
             
            // Gán dữ liệu cho các dấu chấm hỏi (?)
            pstmt.setInt(1, id);
            
            // Thực thi và kiểm tra số dòng bị ảnh hưởng
            int rowsAffected = pstmt.executeUpdate();
            return rowsAffected > 0;
            
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }
}
